language: ruby
rvm:
  - 2.3.0
before_install:
  - gem install selenium-webdriver
services:
  - postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database rubyroid_finance_test' -U postgres